version: '3'
services:
  db:
    image: postgis/postgis:16-3.3  # Use the PostGIS image with PostgreSQL 16 and PostGIS 3.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data